# Usando Numpy

*Entendo que já está com a biblioteca instala, agora podemos importar*

In [2]:
import numpy as np

*Numpy possui muitas funções, então não vamos falar sobre todas mas pelo menos as básica*

**Criando uma lista em Python**

In [3]:
lista = [1,2,3]

In [4]:
lista

[1, 2, 3]

**Convertendo está lista em um array numpy**

In [5]:
np.array(lista)

array([1, 2, 3])

*Criando uma matriz em Python*

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

Convertendo a matriz em uma array 2d

In [7]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Arange**

Criar uma array dentro de um determinado intervalos

In [8]:
# Criando um array de 0 a 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Criando um array de 0 a 11 com intervalo de 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Random**

Criar valores aleatórios 

**rand** *Cria uma array com valores aleatórios entre o intervalo 0 e 1*

In [10]:
np.random.rand(2)

array([0.09052649, 0.14557405])

In [11]:
np.random.rand(4,4)

array([[0.12504078, 0.11334175, 0.73734361, 0.89912121],
       [0.96394855, 0.01722985, 0.29397814, 0.58260192],
       [0.40422777, 0.15571608, 0.97726008, 0.32782546],
       [0.62452935, 0.02322044, 0.42890055, 0.30791721]])

**randint** *Retorna um valor inteiro dentro de um intervalo* 

In [12]:
# Retornar um valor entre 1 e 10
np.random.randint(1,10)

3

In [13]:
# Retornar 5 valores entre 1 e 0
np.random.randint(1,50,5)

array([46,  2, 16, 18, 12])

**randn** *Retorna valores reais*

In [14]:
np.random.randn(2)

array([ 1.53015673, -0.39361676])

In [15]:
np.random.randn(10,10)

array([[ 2.64662763e-01, -2.06826284e+00,  4.70068135e-01,
        -1.51470531e+00,  9.51762635e-01,  5.99883945e-01,
        -1.95221871e-01,  1.86092638e+00,  6.07134088e-01,
        -1.01604248e+00],
       [ 1.17970827e+00, -1.35849811e+00, -1.59910063e-01,
        -1.55025907e+00, -2.22315810e-01,  2.48632099e+00,
        -2.54827711e-01,  1.10577239e+00, -7.42441734e-01,
        -2.30600493e+00],
       [ 1.09169998e-01,  8.41400686e-02,  1.32433441e+00,
        -7.98139603e-01, -1.02264331e+00,  6.92923911e-02,
         1.16472832e+00, -8.46559184e-01, -6.09120323e-01,
         1.15719786e+00],
       [ 8.91382073e-01,  1.36152287e+00, -5.21550493e-01,
         1.39426847e+00,  3.00580472e-01, -3.57599417e-01,
         4.01336746e-01,  1.46701049e+00,  8.22211394e-02,
        -3.32633762e-01],
       [-6.06812030e-02, -7.00527594e-01,  6.98373964e-02,
        -1.48606985e-02,  2.40086169e-01,  2.09328124e-01,
        -1.05424938e-01, -3.19763240e-01, -1.87752769e-01,
        -9.

**linspace**

*Retorna valores dentro de um intervalo com o espaçamento equivalente*

In [16]:
#Retornar 3 números entre 0 e 15, com o intervalo entre eles equivalentes
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [17]:
#Retornar 30 números entre 0 e 15, com intervalos entre eles equivalentes
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

**max, min, argmax, argmin**

Encontrando os maiores valores e os menores e os índices

In [25]:
# Criando um Array 2d com 10 linhas e 5 colunas
array2d = np.random.randn(10,5)

In [26]:
array2d

array([[-0.16629008,  1.17721885,  0.89629024,  0.25532001, -0.49918673],
       [-1.10277525, -1.18027048, -0.58918792,  0.21134711,  0.66859752],
       [-0.34866626, -0.62512982, -0.84322387,  1.78178358,  0.85442565],
       [-0.79700402,  0.71263227, -0.40114261, -0.23507668,  0.38515652],
       [ 0.9248373 ,  0.17362588,  0.14482124,  0.07315733, -0.27139341],
       [-0.53708953,  0.40334334, -0.20435623,  0.34587786,  0.10268947],
       [-0.07251559, -0.27902243, -0.07680294, -0.54042376,  1.02755476],
       [ 2.10900255,  0.04592982, -0.02471291, -1.21783027,  0.06832875],
       [-0.07298389,  0.7474004 ,  0.04317739,  0.87973019,  0.65222261],
       [-1.25898157,  1.95593586,  1.52577335,  0.68910172, -0.54321504]])

In [28]:
#Encontrando o maior valor do array
array2d.max()

2.109002553463747

In [30]:
#Econtrando o menor valor do array
array2d.min()

-1.2589815688116874

In [32]:
#Encontrando o índice do maior valor
array2d.argmax()

35

In [33]:
#Encontrando o índice do menor valor
array2d.argmin()

45

**Seleção**

In [34]:
array = np.arange(1,20)

In [35]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [37]:
# verificando os números maiores que 5 e retornando uma resposta booleana
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
# Selecionando um valor pelo o índice do array
array[1]

2

In [41]:
#Selecionando os valores do índice 9 até o índice 14
array[9:14]

array([10, 11, 12, 13, 14])