# Usando Numpy

*Entendo que já está com a biblioteca instala, agora podemos importar*

In [1]:
import numpy as np

*Numpy possui muitas funções, então não vamos falar sobre todas mas pelo menos as básica*

**Criando uma lista em Python**

In [2]:
lista = [1,2,3]

In [3]:
lista

[1, 2, 3]

**Convertendo está lista em um array numpy**

In [4]:
np.array(lista)

array([1, 2, 3])

*Criando uma matriz em Python*

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

Convertendo a matriz em uma array 2d

In [6]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Arange**

Criar uma array dentro de um determinado intervalos

In [7]:
# Criando um array de 0 a 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Criando um array de 0 a 11 com intervalo de 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Random**

Criando valores aleatórios 

**rand** *Cria uma array com valores aleatórios entre o intervalo 0 e 1*

In [9]:
np.random.rand(2)

array([0.54438407, 0.26914641])

In [10]:
np.random.rand(4,4)

array([[0.14308964, 0.77315232, 0.19181214, 0.61638557],
       [0.07760024, 0.8136501 , 0.90847205, 0.56483701],
       [0.81204207, 0.99270522, 0.72513477, 0.08679994],
       [0.63015005, 0.68111338, 0.68705344, 0.32420526]])

**randint** *Retorna um valor inteiro dentro de um intervalo* 

In [11]:
# Retornar um valor entre 1 e 10
np.random.randint(1,10)

2

In [12]:
# Retornar 5 valores entre 1 e 0
np.random.randint(1,50,5)

array([24, 14, 44, 16, 18])

**randn** *Retorna valores racionais*

In [28]:
np.random.randn(2)

array([-1.23239987,  1.13158967])

In [14]:
np.random.randn(10,10)

array([[ 0.28621045,  0.00427868, -0.70353339,  2.40540728,  1.92620137,
         1.35237995,  0.18866182,  0.31432204,  1.18167042,  0.45401236],
       [-1.16861107,  0.13348937, -1.37183523, -0.27618235, -1.93915637,
         0.36427394, -0.03090928,  0.15266287,  1.34480517,  2.03447337],
       [-0.92802395, -0.03281556, -1.93553991, -0.80161308,  0.18626227,
         1.45975974, -0.99902458,  0.36748042,  0.20480076,  0.46261404],
       [ 0.49452121,  0.60007717,  0.35971942, -0.94826101,  0.93746364,
         0.76249878, -1.83907076,  1.18283051,  0.92380337,  2.16331255],
       [-0.11313352,  0.54406263,  0.36111319,  0.49286564, -0.42250636,
         0.29195918, -1.04978003, -0.40410473,  0.74617889, -0.45975425],
       [ 0.21180438,  0.45997427,  1.6652985 ,  1.06147862,  0.63006234,
        -0.02328572,  0.04310087, -0.22539823,  0.25427752,  0.50218245],
       [-0.10060933, -0.03246279,  1.72487915, -0.25157329, -0.01071305,
        -0.15565117,  0.39847088,  0.70442817

**linspace**

*Retorna valores dentro de um intervalo com o espaçamento equivalente*

In [15]:
#Retornar 3 números entre 0 e 15, com o intervalo entre eles equivalentes
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [16]:
#Retornar 30 números entre 0 e 15, com intervalos entre eles equivalentes
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

**max, min, argmax, argmin**

Encontrando os maiores valores e os menores e os índices

In [17]:
# Criando um Array 2d com 10 linhas e 5 colunas
array2d = np.random.randn(10,5)

In [18]:
array2d

array([[-1.71729759e+00,  1.18061753e-01, -1.23511646e+00,
        -1.29456380e+00,  2.04501928e-01],
       [ 5.00082810e-01, -1.64403800e+00, -1.33189171e+00,
        -6.80052613e-01,  4.94661132e-01],
       [ 7.57612107e-01,  3.31945390e-01,  1.30629200e+00,
         4.50799500e-01, -2.18308306e-01],
       [ 7.81980841e-01,  9.61331081e-01, -1.41242317e-01,
         8.42142346e-01, -5.78606694e-01],
       [-1.62665292e+00, -6.81911481e-01, -2.78781281e-01,
         1.35850836e+00, -1.01911670e+00],
       [-1.30780876e-03, -7.19600190e-01, -1.74147905e+00,
        -3.50006769e+00,  3.65473676e-01],
       [ 1.89897991e+00, -7.05744397e-01,  5.09817599e-01,
         3.01997515e-01, -6.41740464e-01],
       [-3.76978568e-01, -1.63235266e+00,  1.35520439e+00,
         7.98410490e-01, -3.76699916e-02],
       [ 1.93528246e+00, -7.88569345e-01, -4.54378069e-01,
         1.29051356e+00, -1.03220727e+00],
       [ 4.10772851e-01,  1.22054362e+00, -1.41050335e+00,
         9.11642304e-01

In [19]:
#Encontrando o maior valor do array
array2d.max()

1.935282457519985

In [20]:
#Econtrando o menor valor do array
array2d.min()

-3.5000676927351266

In [21]:
#Encontrando o índice do maior valor
array2d.argmax()

40

In [22]:
#Encontrando o índice do menor valor
array2d.argmin()

28

**Seleção**

In [23]:
array = np.arange(1,20)

In [24]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [25]:
# verificando os números maiores que 5 e retornando uma resposta booleana
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
# Selecionando um valor pelo o índice do array
array[1]

2

In [27]:
#Selecionando os valores do índice 9 até o índice 14
array[9:14]

array([10, 11, 12, 13, 14])