# Usando Numpy

*Entendo que já está com a biblioteca instala, agora podemos importar*

In [1]:
import numpy as np

*Numpy possui muitas funções, então não vamos falar sobre todas mas pelo menos as básica*

**Criando uma lista em Python**

In [3]:
lista = [1,2,3]

In [4]:
lista

[1, 2, 3]

**Convertendo está lista em um array numpy**

In [5]:
np.array(lista)

array([1, 2, 3])

*Criando uma matriz em Python*

In [11]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

Convertendo a matriz em uma array 2d

In [12]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Arange**

Criar uma array dentro de um determinado intervalos

In [13]:
# Criando um array de 0 a 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Criando um array de 0 a 11 com intervalo de 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Random**

Criar valores aleatórios 

**rand** *Cria uma array com valores aleatórios entre o intervalo 0 e 1*

In [19]:
np.random.rand(2)

array([0.05234678, 0.83924005])

In [21]:
np.random.rand(4,4)

array([[0.87925733, 0.34828982, 0.72332032, 0.65719573],
       [0.88619373, 0.97366709, 0.54678541, 0.29499133],
       [0.35458358, 0.856052  , 0.69452188, 0.83719404],
       [0.04136745, 0.97479076, 0.39840837, 0.2431519 ]])

**randint** *Retorna um valor inteiro dentro de um intervalo* 

In [24]:
# Retornar um valor entre 1 e 10
np.random.randint(1,10)

1

In [27]:
# Retornar 5 valores entre 1 e 0
np.random.randint(1,50,5)

array([11, 48,  2, 26, 16])

**randn** *Retorna valores reais*

In [28]:
np.random.randn(2)

array([-0.89831491,  0.60741049])

In [29]:
np.random.randn(10,10)

array([[ 7.57315811e-01,  3.80732990e-01,  3.43702555e-01,
         1.70541732e-01,  1.83624382e-01,  7.90731470e-01,
        -7.36081363e-01,  2.94282752e-01, -6.22882663e-01,
         7.84660957e-01],
       [ 4.89261260e-01, -1.07778072e+00,  2.57595748e-01,
         1.93350187e-01, -8.90451348e-01, -6.03598395e-01,
         3.52651735e-01,  3.05044410e-01, -7.04982871e-01,
        -1.19366699e+00],
       [-8.54782784e-01, -7.86097796e-01, -1.32127945e+00,
         2.32245793e+00,  2.50465356e+00,  1.02345982e+00,
        -2.25231372e-01,  2.51926682e-01,  1.17269546e+00,
         8.24568048e-01],
       [-1.55892206e+00,  3.68565967e-01, -9.46475672e-02,
        -3.41923838e+00, -1.92943824e+00, -1.08325158e+00,
         3.52241519e-01, -1.68332444e+00,  1.01981549e+00,
         1.25391587e+00],
       [ 1.05315357e+00,  2.98900046e-01, -1.59052654e+00,
        -2.54141884e-02, -1.50364484e+00,  3.78979676e-01,
        -1.33399658e+00,  1.76324564e-01, -2.94051180e-01,
        -1.

**linspace**

*Retorna valores dentro de um intervalo com o espaçamento equivalente*

In [31]:
#Retornar 3 números entre 0 e 15, com o intervalo entre eles equivalentes
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [34]:
#Retornar 30 números entre 0 e 15, com intervalos entre eles equivalentes
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])